title:  kodemu
tagline:  eat, code, pray
author:
  name: 'kodemu'
  twitter:  kodemu

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID:

menu:
# - {name: 'home', url: '/'}
# - {name: 'Writing', url: 'writing.html'}
# - {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/kodemu'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
# - {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
# - {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
